services:
  # Backend Laravel API
  - type: web
    name: catalogo-api
    runtime: php@8.1
    buildCommand: >
      curl -sS https://getcomposer.org/installer | php &&
      php composer.phar install --no-dev &&
      php artisan migrate --force
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          type: web
          name: catalogo-api
          envVarKey: RENDER_EXTERNAL_URL
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: catalogo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: catalogo-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: catalogo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: catalogo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: catalogo-db
          property: password
      - key: LOG_CHANNEL
        value: stack
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120
    healthCheckPath: /api/test
    repo: https://github.com/pablovirtual/fullstack-catalogo-peliculas
    branch: master
    rootDir: backend/catalogo

  # Frontend Angular Application
  - type: web
    name: catalogo-frontend
    runtime: node@16
    buildCommand: >
      npm ci &&
      sed -i "s|API_URL|$API_URL|g" src/environments/environment.prod.ts &&
      npm run build
    startCommand: npx serve -s dist/catalogo-peliculas
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          type: web
          name: catalogo-api
          envVarKey: RENDER_EXTERNAL_URL
    repo: https://github.com/pablovirtual/fullstack-catalogo-peliculas
    branch: master
    rootDir: frontend/catalogo-peliculas

databases:
  - name: catalogo-db
    databaseName: catalogo
    user: catalogo
    plan: free
