services:
  # Backend Laravel API
  - type: web
    name: catalogo-api
    env: php
    rootDir: backend/catalogo
    buildCommand: "composer install && npm install && npm run build && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        fromService:
          name: catalogo-api
          type: web
          property: host
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: catalogo-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: catalogo-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: catalogo-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: catalogo-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: catalogo-db
          property: password
      - key: LOG_CHANNEL
        value: stack
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_LIFETIME
        value: 120
      # Enable CORS for Angular frontend
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          name: catalogo-frontend
          type: web
          property: host

  # Frontend Angular Application
  - type: web
    name: catalogo-frontend
    env: node
    rootDir: frontend/catalogo-peliculas
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist/catalogo-peliculas
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        fromService:
          name: catalogo-api
          type: web
          property: host

databases:
  - name: catalogo-db
    databaseName: catalogo
    user: catalogo
    plan: free
